[package]
name = "adv-code-2024"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Jean-Sébastien Gonsette"]

[dependencies]
anyhow = "1.0.93"
itertools = "0.13.0"
nalgebra = "0.33"
num = "0.4"
svg = "0.18"
rayon = "1.10.0"
